version: "3.7"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nodejs-training
    expose:
      - 3333
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    command: npm run dev
    links:
      - db
    depends_on:
      - db
volumes:
  pgdata:
    driver: local
