version: "3.7"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
